# Functions

In [1]:
import pandas as pd
import seaborn as sb
import numpy as np

In [ ]:
sb.get_dataset_names()

In [2]:
tips = sb.load_dataset("tips")
titanic=sb.load_dataset("titanic")
products=pd.read_csv("data/products.csv")
pup = pd.read_csv('data/Pupils.csv')
orders = pd.read_excel("data/orders.xlsx")
cust = pd.read_csv("data/Customers.csv")

In [ ]:
tips.head()

In [ ]:
pup.head()

# String Functions

In [4]:
#Get the first row
pup["Name"][0:3]

0    adar
1    agam
2     avi
Name: Name, dtype: object

In [8]:
pup.iloc[0:4]

   Name  Age Country  Height  Weight  avg  income  rooms  family  type gen
0  adar    6      SP     113      30   70   16700      7       6     1   M
1  agam    6      GR     172      71   92    9200      5       4     2   F
2   avi    7     ISR     143      58   82   12000      3       7     1   M
3  dani    7      US     160      70   90   15000      4       4     2   M

In [10]:
pup["Name"].str[0:2].head()

0    ad
1    ag
2    av
3    da
4    di
Name: Name, dtype: object

In [ ]:
#slice() - Slice substrings from each element in the Series or Index.
#Substring in sql

In [13]:
pup["Name"].str.slice(0).head()

0    adar
1    agam
2     avi
3    dani
4    dina
Name: Name, dtype: object

In [ ]:
pup["Name"][0:3]

In [14]:
pup["Name"].str.slice(1,3).head()

0    da
1    ga
2    vi
3    an
4    in
Name: Name, dtype: object

In [15]:
pup["Name"].str.slice(0,6,2).head()

0    aa
1    aa
2    ai
3    dn
4    dn
Name: Name, dtype: object

In [ ]:
pup["Name"].head()

In [16]:
pup["Name"].str.slice(-1).head()

0    r
1    m
2    i
3    i
4    a
Name: Name, dtype: object

In [17]:
pup["Name"].to_frame().assign(First_char= pup["Name"].str.slice(0,2)).head()

   Name First_char
0  adar         ad
1  agam         ag
2   avi         av
3  dani         da
4  dina         di

In [18]:
pup["Name"].head().to_frame().assign(First_char= pup["Name"].str.slice(0,2))

   Name First_char
0  adar         ad
1  agam         ag
2   avi         av
3  dani         da
4  dina         di

In [19]:
pup["Name"].str.len().head()

0    4
1    4
2    3
3    4
4    4
Name: Name, dtype: int64

In [20]:
pup["Name"].to_frame().assign(len=pup["Name"].str.len()).head()

   Name  len
0  adar    4
1  agam    4
2   avi    3
3  dani    4
4  dina    4

In [ ]:
pup["Name"].assign()

In [21]:
s =pd.Series(['1.  Hello    ','2.  World!\n ','3.  python.\t' ])

In [22]:
s

0    1.  Hello
1    2.  World!\n
2    3.  python.\t
dtype: object

In [23]:
#Remove spaces at the beginning and at the end of the string
#trim in sql
s.str.strip()

0      1.  Hello
1     2.  World!
2    3.  python.
dtype: object

In [ ]:
s.str.lstrip('123. ')

In [ ]:
s.str.rstrip('!.\n\t ')

In [ ]:
s.str.strip('123!.\n\t ')

In [28]:
"v1-"+s.str.strip(" 123.\n\t")+"-v2"

0     v1-Hello-v2
1    v1-World!-v2
2    v1-python-v2
dtype: object

In [24]:
s.str.title()

0    1.  Hello
1    2.  World!\n
2    3.  Python.\t
dtype: object

In [25]:
pup["Name"].head(20)

0        adar
1        agam
2         avi
3        dani
4        dina
5       efrat
6        ehud
7         eli
8       ester
9     evyatar
10     itamar
11       liel
12     lilach
13        mia
14     michal
15      moshe
16       noya
17       ofer
18       ohad
19       omer
Name: Name, dtype: object

In [27]:
pup["Name"].str.strip('ae').head(10)

0       adar
1       agam
2        avi
3       dani
4       dina
5      efrat
6       ehud
7        eli
8      ester
9    evyatar
Name: Name, dtype: object

In [ ]:
#replace

In [ ]:
pup["Name"].str.replace('a','_').head()

In [ ]:
#upper() , lower() , title()

In [ ]:
pup["Name"].str.upper().head()

In [ ]:
pup["Name"].str.lower().head()

In [ ]:
pup["Name"].str.title().head()

In [31]:
pup["Name"].to_frame().assign(initcap=pup["Name"].str.title()).head()

   Name initcap
0  adar    Adar
1  agam    Agam
2   avi     Avi
3  dani    Dani
4  dina    Dina

In [30]:
pup

       Name  Age Country  Height  Weight  avg  income  rooms  family  type gen
0      adar    6      SP     113      30   70   16700      7       6     1   M
1      agam    6      GR     172      71   92    9200      5       4     2   F
2       avi    7     ISR     143      58   82   12000      3       7     1   M
3      dani    7      US     160      70   90   15000      4       4     2   M
4      dina    7     ISR     110      26   64   10000      6       8     1   F
5     efrat    7      EN     115      33   75    8000      5       5     3   F
6      ehud    8     ISR     155      66   85   18000      2       7     1   M
7       eli    8      GR     155      61   84    8900      7      10     2   M
8     ester    8     ISR     130      48   79   19600      2       4     1   F
9   evyatar    8     ISR     110      34   72    7600      3       4     1   M
10   itamar    8      EN     110      30   71   27000      2       5     2   M
11     liel    8     ISR     142      55   84   24000      2       7     1   M
12   lilach    9     ISR     192      88   94   23000      5       6     2   F
13      mia    9      GR     132      49   82   12800      4       5     3   F
14   michal    9      US     132      53   79   20400      5       7     3   F
15    moshe    9      GR     128      43   80   42000      6       5     3   M
16     noya    9      SP      90      27   68   18200      6       5     1   F
17     ofer   10      SP     110      34   71    9300      4       8     1   M
18     ohad   10     ISR     159      64   83   12700      4       8     1   M
19     omer   10      US     162      68   87   34500      6       8     2   F
20     orit   10      US     123      40   78   18900      3       7     3   F
21     orit   11     ISR     175      73   89   54100      4       3     2   F
22     rina   11      EN     100      31   73   30000      2       5     3   F
23    shely   11     ISR     148      60   86    8000      4       3     1   F
24    talya   12      FR     167      67   89   10900      6       6     2   F
25    tomer   12      FR     128      53   82   45000      5       4     3   M
26      udi   13      FR     147      55   85   35000      7       6     2   M
27    yafit   13      FR     180      90   93   12800      2       4     1   F
28     yoav   13      EN     120      36   74   17300      5       8     3   M
29     yosi   14      SP     110      32   74   22000      5       6     1   M

In [ ]:
x=pd.DataFrame(['hello word'])

In [ ]:
#x.str.title()

In [ ]:
mask = pup["Name"].str.lower()=='agam'

In [ ]:
pup[mask]

In [ ]:
s

In [ ]:
s =pd.Series(['Hello World', "Hi Python"])

In [ ]:
s

In [ ]:
s.str.split(' ')

In [ ]:
s.to_frame()

In [ ]:
s.to_frame().assign(a =s.str.split(' ').str[0],
                    b=s.str.split(' ').str[-1])

In [ ]:
pup.head()

In [ ]:
products.head()

In [ ]:
products["ProductName"].str.split()

In [ ]:
products["ProductName"].str.split(expand=True)

In [ ]:
products["ProductName"].str.split(expand=True)[0]

In [ ]:
products["start name"]=products["ProductName"].str.split(expand=True)[0]

In [ ]:
products.head()

In [ ]:
products["ProductName"].str.initcap()

# Numeric Functions

In [ ]:
#round()

In [ ]:
pup.head()

In [ ]:
tips.head()

In [ ]:
np.round(tips["total_bill"],0)

In [ ]:
tips["total_bill"].round(1).head()

In [ ]:
np.floor(tips["total_bill"]).head()

In [ ]:
np.ceil(tips["total_bill"]).head()

In [ ]:
#mul = Multiply DataFrames., div = Divide DataFrames

In [ ]:
np.ceil(tips["total_bill"].mul(100)).div(100).head()

# Date Functions

In [ ]:
products=pd.read_csv("data/products.csv")

In [ ]:
products.head(20)

In [ ]:
products.info()

In [40]:
products["Date"]=pd.to_datetime(products["Date1"],format="%d/%m/%Y")

In [ ]:
products.info()

In [ ]:
products.head(30).sort_values("Date")

In [39]:
import datetime as dt

In [ ]:
pd.Timestamp.today()

In [41]:
products["Date"].dt.year.head()

0    2022
1    2022
2    2022
3    2022
4    2022
Name: Date, dtype: int64

In [ ]:
products.assign(year1 =products["Date"].dt.year,).head()

In [44]:
products["MM"]=products["Date"].dt.month.astype('int')

In [45]:
products.head()

,ProductID,ProductName,UnitPrice,CategoryID,Date1,Date2,Date,MM
0,1,Chai,18.00,1,05/12/2022,15/12/2022,2022-12-05,12
1,2,Chang,19.00,1,06/12/2022,16/12/2022,2022-12-06,12
2,3,Aniseed Syrup,10.00,2,07/12/2022,17/12/2022,2022-12-07,12
3,4,Chef Anton's Cajun Seasoning,22.00,2,08/12/2022,18/12/2022,2022-12-08,12
4,5,Chef Anton's Gumbo Mix,21.35,2,09/12/2022,19/12/2022,2022-12-09,12

In [ ]:
products["Date"].dt.day.head()

In [ ]:
(products["Date"] + pd.DateOffset(days=1)).head()

In [ ]:
(products["Date"] - pd.DateOffset(days=1,months=2,years=2)).head()

In [ ]:
(products["Date"] - pd.Timestamp.today()).head()

In [ ]:
orders.head()

In [ ]:
orders.info()

In [ ]:
timedelta_day=pd.Timestamp.today() -orders["OrderDate"]

In [ ]:
timedelta_day.dt.days/365

In [ ]:
#timedelta— A duration of time used for manipulating dates

In [ ]:
ld = pd.Timestamp.today()
td=np.timedelta64(1,'Y')
print(td)

In [ ]:
ld = pd.Timestamp.today()
td=np.timedelta64(1,'M')
print(td)

In [ ]:
ld = pd.Timestamp.today()
td=np.timedelta64(1,'D')
print(td)

In [ ]:
(products["Date"]-ld)/td

In [ ]:
timedelta_day/ td

# Convert Functions

In [ ]:
num_s = '$1345.0'
type(num_s)

In [ ]:
num = num_s.replace('$','')
print(num)
type(num)

In [ ]:
num1 =pd.to_numeric(num)

In [ ]:
num1

In [ ]:
type(num1)

In [ ]:
type(num)

In [ ]:
#the resulting numeric values should be downcast to the integer type if possible.
num2=pd.to_numeric(num1, downcast="integer")

In [ ]:
print(num2)

In [ ]:
type(num2)

In [ ]:
n1='1,450'

In [ ]:
type(n1)

In [ ]:
n1=pd.to_numeric(n1)

In [ ]:
type(n1)

In [ ]:
n1=pd.to_numeric(n1,downcast='integer')

In [ ]:
n1=pd.to_numeric(n1,errors='ignore',downcast='integer')

In [ ]:
type(n1)

In [ ]:
n1

In [ ]:
n2 =n1.replace(',','')

In [ ]:
n2

In [ ]:
type(n2)

In [ ]:
n2=pd.to_numeric(n2)

In [ ]:
n2

In [ ]:
type(n2)

#Convert String to_datetime

In [32]:
dt1 = '31-12-2018'

In [33]:
type(dt1)

str

In [34]:
dt2 =pd.to_datetime(dt1)

C:\Users\Sima\AppData\Local\Temp\ipykernel_6668\4037734424.py:1: UserWarning: Parsing dates in DD/MM/YYYY format when dayfirst=False (the default) was specified. This may lead to inconsistently parsed dates! Specify a format to ensure consistent parsing.
  dt2 =pd.to_datetime(dt1)

In [35]:
type(dt2)

pandas._libs.tslibs.timestamps.Timestamp

In [36]:
dt2.year

2018

In [37]:
dt2.month

12

In [38]:
dt2.day

31

In [ ]:
#Convert to string

In [ ]:
#astype(str)

In [ ]:
products["Date"] = products["Date"].astype('str')

In [ ]:
products["Date"]

In [ ]:
products.info()

In [ ]:
products

In [ ]:
df['Numbers'] = df['Numbers'].astype(int)
df['Numbers'] = df['Numbers'].astype(float)
df['Numbers'] = df['Numbers'].astype(str)

In [ ]:
#Nulls

In [ ]:
cust.head(5)

In [ ]:
cust[["CustomerID","CompanyName","Region"]].head()

In [ ]:
ifnull =cust["Region"].isnull()

In [ ]:
cust[ifnull].head()

In [ ]:
ifnotnull =cust["Region"].notnull()

In [ ]:
cust[ifnotnull].head()

In [ ]:
#Filling null values with the previous ones -- fillna()

In [ ]:
df["Region"] = df["Region"].fillna("No Region")

In [ ]:
cust.head(5)

In [ ]:
#Dropping missing values using dropna()

In [ ]:
cust.count()

In [ ]:
a= cust["PostalCode"].isnull()

In [ ]:
cust[a].head()

In [ ]:
#drop all rows that have any NaN values
dn=cust.dropna()

In [ ]:
dn.head()

In [ ]:
dn.count()

In [ ]:
 #drop only if ALL columns are NaN
dn1=cust.dropna(how='all')

In [ ]:
dn1.count()

In [ ]:
#Drop only if NaN in specific column (as asked in the question)
dn2=cust.dropna(subset=["PostalCode"])

In [ ]:
dn2.count()